pipeline {
    agent {
        node {
            label 'agent'
        }
    }
    environment {
        COURSE = "Jenkins"
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-ecr') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('Plan') {
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-ecr') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Chakradhar', description: 'Who should I say hello to?')
                }
            }
            
            steps {
                script{
                    withAWS(region:'us-east-1',credentials:'aws-ecr') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }
    post{
        always{
            echo 'I will always say Hello again!'
        }
        success {
            echo 'I will run if success'
        }
        failure {
            echo 'I will run if failure'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}
